### PR TITLE
Manage Data Stream

### PR DESCRIPTION
**Pull request by mgoacolou**
This PR give ability to manage data stream 

there is an  issue with stream because there is not codec for this kind of data so the properties "codec", "type" and name must be defined.

### CODE REVIEW

**Comment by mikeboers** [comment]
Thanks for this.

I'm curious, what are you able to do with this except know that the data stream exists? I suppose then you can identify packets and look at the raw data...

**Comment by mgoacolou** [comment]
With this, we are able to read Full Motion Video/ MISB video and extract geo information (center of image, corners, ...) of frames

**Comment by mgoacolou** [comment]
for example: https://community.esri.com/docs/DOC-8527

**Comment by mgoacolou** [comment]
Hi,
Do you plan to merge this Pull Request.

**Comment by mikeboers** [comment]
Yes, when I have the time.

**Pull request closed without merging**
