### PR TITLE
Expose Frame Sidedata

### PR DESCRIPTION
**Pull request by mikeboers**
I wasn't too keen on #557 (because it appeared to be tailored to a specific use-case), but it did show me how to work with side data, so I whipped this together.

Thoughts, anyone?

### CODE REVIEW

**Comment by RouquinBlanc** [comment]
Hi Mike!

Indeed, this looks much more generic than my crafty attempt at Cython! But you got my point and I'm very happy to see that integrated, thanks a lot! I will give it a try ASAP

**Comment by RouquinBlanc** [comment]
I can confirm getting similar results with the C equivalent. And also still being able to get the whole list as an ndarray is much appreciated! 👍

**Comment by mikeboers** [comment]
The way I padded out the array is kinda weird. Why does `sizeof(AVMotionVector)` not equal what it looks like it should? I feel like that needs to be figured out, or generalized in some way.

**Comment by mikeboers** [comment]
[`numpy.dtype` has an `align` parameter](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dtype.html#numpy.dtype) which is what I need. Hooray!

**Comment by rohit-gupta** [comment]
Being able to extract motion vectors without writing C code would be a great feature !

**Pull request merged**
