### PR TITLE
fixed an error in accessing extradata size

### PR DESCRIPTION
**Pull request by adavoudi**
'av.bytesource.ByteSource' object has no attribute 'size'. We need to change it to length in this line.

### CODE REVIEW

**Comment by jlaine** [comment]
Looks like a good catch. Could you please include a minimal unit test (in `tests/test_codec_context.py`) in your PR so this breakage doesn't silently creep back in at a later date?

**Comment by adavoudi** [comment]
Could you please accept this PR without the unit test part as I'm not sure how to create a unit test for this functionality.

**Comment by jlaine** [comment]
If you have reported this issue, you have certainly encountered it, so you are in a unique position to capture the conditions that triggered the problem.

There is no rush to just merge an incomplete PR, let's get it done right.

**Comment by jlaine** [comment]
Please refrain from adding unrelated changes to this PR: keep the PR focused on the initial issue, add tests to it and ensure continuous integration passes so we can move forward.

If this PR turns into a dumping ground for unrelated changes it has no chance of landing.

**Comment by jlaine** [comment]
ping @adavoudi ? Can I just have a simple example of how one uses extradata?

**Comment by mikeboers** [comment]
This was just fixed.

**Pull request closed without merging**
