### PR TITLE
Remove legacy-style buffer protocol from Buffer

### PR DESCRIPTION
**Pull request by jlaine**

### CODE REVIEW

**Comment by jlaine** [comment]
Well, that failed spectacularly..

**Comment by mikeboers** [comment]
If I understand the situation:

- Numpy on Py2 uses the old-style buffer.
- The old-style buffer does not have dimensions, although we could hack on strides.
- You said something on Gitter about `the cython code I wrote which copies partial rows in strides is probably just as efficient`, but I don't know what you're referring to. I'm not seeing the copying. Maybe I need more coffee.

**Comment by jlaine** [comment]
I was referring to :

https://github.com/mikeboers/PyAV/blob/304b6f9fcb24156a7ef7c7445dd573fb3f74e949/av/video/frame.pyx#L318

and

https://github.com/mikeboers/PyAV/blob/304b6f9fcb24156a7ef7c7445dd573fb3f74e949/av/video/frame.pyx#L394

**Comment by mikeboers** [comment]
Oh okay cool. I'll admit I've never used the Cython memory view (or whatever) syntax before, and just didn't spot it at a glance. Thanks for dealing with me.

I agree with that being reasonably efficient. The lesson is that PIL/Pillow is not efficient. 😉

**Comment by jlaine** [comment]
I'm closing this PR, we can revisit this at a future date.

**Pull request closed without merging**
