### PR TITLE
Build on Py35, Win64

### PR DESCRIPTION
**Pull request by caspervdw**
After some hours of tinkering (thanks @beville for the helpful notes in #156), I got PyAV working on my Win64 laptop with Python 35, using the binaries from https://ffmpeg.zeranoe.com/builds/ .
## Prerequisites
- Python35 on Windows is compiled using MSVC14, which can be obtained from Microsoft for free in the 'Visual C++ Build Tools 2015'. Using `setuptools>=0.24`, compiling and linking worked out-of-the-box for me. See [here](https://wiki.python.org/moin/WindowsCompilers) for more info.
- Both the shared (for running) and dev (for compiling) packages ([link](https://ffmpeg.zeranoe.com/builds/)), extracted in the same folder (e.g. C:\ffmpeg). Make sure C:\ffmpeg\bin and C:\ffmpeg\lib and C:\ffmpeg\include exist.
- Add the ffmpeg `bin` folder to the PATH environment variable (e.g. C:\ffmpeg\bin)
- Install Cython (?)
- `git clone` or download & extract PyAV source
## Build

From within the PyAV source directory

```
python setup.py build_ext --inplace --ffmpeg-dir=C:\ffmpeg
```

or

```
set FFMPEG_DIR=C:\ffmpeg
python setup.py build_ext --inplace`
```

This builds PyAV against a specific build of ffmpeg. Changing the ffmpeg binaries will get you a `DLL not found` error on import.
## Test
- `nosetests` pass
- PIMS `nosetests` pass

I would like to get the wheel on conda, but as it is compiled against a specific ffmpeg version, these libraries would ideally be included. I am not sure how to do that properly.

### CODE REVIEW

**Comment by caspervdw** [comment]
I added a workaround for a MANIFEST issue with the MSVC10 compiler, so it should now work on all python versions, as confirmed by Appveyor. The appveyor is failing now only due to a missing PIL install, it seems like the conda recipe is also not OK. But that is something for a different PR.

MSVC10 needs the `msinttypes` patch. Easiest would be shipping these two small header files with PyAV. What do you think?

**Comment by caspervdw** [comment]
Appveyor passes!!

**Comment by mikeboers** [comment]
This is wonderful! Thank you.

I'm hoping to have a PyAV sprint in the near future so I can pull this in, along with a couple other open issues.

**Comment by caspervdw** [comment]
I am happy to contribute to this great project!

I will clean the unused appveyor scripts and `dev-requirements.txt` in a next commit.

It would be great if the wheels could be pushed to a public wheelhouse, only there must be some user-friendly way to assert the right ffmpeg version. For completeness, Py3.3 should be done on Appveyor too.

**Comment by caspervdw** [comment]
@mikeboers   Any chance to get this in soon? I would really like to implement the windows build on conda-forge so that PyAv will install via conda on windows.

**Comment by mikeboers** [comment]
Yes. I'm sorry to leave this hanging. I finally forced myself to read it and it generally looks wonderful. You've added some helpful stuff to the build process in general.

🍻

**Comment by danielballan** [comment]
@mikeboers Would now be a good time to tag v0.3.2?

Once these changes are available in a tagged release, the [conda-forge recipe](https://github.com/conda-forge/av-feedstock/) should be able to build Windows conda packages on appveyor.

**Comment by caspervdw** [comment]
Thanks @mikeboers, hopefully we can get the conda recipe working soon so that windows-users can start using PyAV!

**Comment by mikeboers** [comment]
Done and done.

Thanks for your patience everyone.

:beers:

**Comment by danielballan** [comment]
Wonderful! Thank you for maintaining this excellent project over the years. Your hard work is very appreciated. :- )

**Comment by mikeboers** [comment]
You're welcome. I just wish I had the time to sit down and flush out a bit more of it. Hopefully I'll find a way for PyAV to be key to some work for one of my clients so I get that chance. 😉

**Comment by danielballan** [comment]
I went to update the conda recipe and realized that we also need a PyPI release for this tag. When you get a moment, could you upload v0.3.2 to PyPI?

**Comment by mikeboers** [comment]
I forgot that part. Just uploaded it now.

**Pull request merged**
