### PR TITLE
Fix travis and appveyor continuous integration

### PR DESCRIPTION
**Pull request by jlaine**
The Python 2.7 builds are bombing:

ImportError: No module named 'setuptools'

### CODE REVIEW

**Comment by jlaine** [comment]
Well, that failed miserably..

**Comment by jlaine** [comment]
Something looks a bit fishy in this build which is supposedly against python 2.7:

https://travis-ci.org/mikeboers/PyAV/jobs/430275109

I see: 

`PYAV_PYTHON=python3`

**Comment by jlaine** [comment]
The commit that seems to have broken the build is : d31e902c948b71c98b2d023422ad72eff1d602a1

**Comment by jlaine** [comment]
The test suite now passes on Travis! This also fixed the build on appveyor for Python 2.7, only 3.5/Windows remains broken.

**Comment by mikeboers** [comment]
I'm so OK with merging it, that I just did it. 😁

**Pull request merged**
